# Generated by Django 2.2.5 on 2021-09-16 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210916_2226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='languge',
            new_name='language',
        ),
    ]
